### PR TITLE
Edit UG, add Ui component to DG

### PR DESCRIPTION
**Pull request by alstontham**
Made some minor edits to the User Guide and converted the Command Summary at the end of the document to a table for easier readability. Currently working on changes for the Ui component of the DG.

### CODE REVIEW

**Review by daniellimws — APPROVED** [review]
Nice!

**Comment by alstontham** [comment]
I refactored the color and UI code in this PR so it can be compared with the UI information in the DG

**Comment by daniellimws** [comment]
In DG it says `ColourManager` but in code we have `Color`.

**Comment by alstontham** [comment]
I haven't finished editing the DG yet, will push some more commits soon!

**Pull request merged**
